// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6tkYOlwpPvRogA-AASyy1p_iByCYOjF0',
    appId: '1:434796898312:web:818fe2c91b79a65ed2c9bd',
    messagingSenderId: '434796898312',
    projectId: 'todo-app-587bb',
    authDomain: 'todo-app-587bb.firebaseapp.com',
    storageBucket: 'todo-app-587bb.appspot.com',
    measurementId: 'G-Q7CC6L1K8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAziUzlSqDcSuoJVJCxvmOanxDKtpfkOC8',
    appId: '1:897336905319:android:cbe8d9ccd35c55fba18ec2',
    messagingSenderId: '897336905319',
    projectId: 'todo-app-11e3d',
    storageBucket: 'todo-app-11e3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAldrsKq9xN6_WfKkhGXKIWj75yyxKPKmo',
    appId: '1:897336905319:ios:13d515c634ff8c40a18ec2',
    messagingSenderId: '897336905319',
    projectId: 'todo-app-11e3d',
    storageBucket: 'todo-app-11e3d.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyWaWQpfUBh5nTFZrL1RhfyMrbJ-VIJ3c',
    appId: '1:434796898312:ios:e72e6deef8d9019dd2c9bd',
    messagingSenderId: '434796898312',
    projectId: 'todo-app-587bb',
    storageBucket: 'todo-app-587bb.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}